version: '3.9'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env.example
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  db-data:
